### PR TITLE
Made macro to replace vfs.h with mount.h for Mac

### PR DESCRIPTION
**Pull request by tibnor**
Replaced

     #include <sys/vsf.h> 
with 

     #  ifdef __APPLE__
     #    include<sys/mount.h>
     #  else
     #    include<sys/vfs.h>
     #  endif

Regarding issue #12

### CODE REVIEW

**Comment by relet** [comment]
Look good to me. Is __APPLE__ defined in the makefiles already?

**Comment by ninsbl** [comment]
Should`nt APPLE be written to Makefile when running "autoreconf"?
I am working on a merge of master and unicode branch at the moment and in this context it would be nice to know if Mac also defines "UNIX" in Makefiles. @tibnor Would you mind checking?

**Comment by tibnor** [comment]
I'm not sure if __APPLE__ should be written to Makefile during "autoreconf". However it is predefined (both for g++ and clang). __unix__ is not predefined on (my) Mac OS X (10.10).

**Comment by jackxujh** [comment]
@tibnor Do you mean `__APPLE__` is predefined in the compiler and we don't need to worry about it in the Makefile?

**Pull request merged**
